# Generated by Django 5.2.4 on 2025-07-17 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(default='Admin', max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('img_path', models.URLField(blank=True, max_length=255, null=True)),
                ('permission', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin')], default='admin', max_length=50)),
            ],
            options={
                'db_table': 'admin_account',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('profile_photo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('current_post', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('blessing', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='FamilyDetail',
            fields=[
                ('family_member_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('blessing', models.CharField(max_length=100)),
                ('member_id', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='directory.member')),
            ],
            options={
                'verbose_name': 'Family Detail',
                'verbose_name_plural': 'Family Details',
                'db_table': 'family_detail',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('penalty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='directory.member')),
            ],
            options={
                'verbose_name': 'Disciplinary Action',
                'verbose_name_plural': 'Disciplinary Actions',
                'db_table': 'disciplinary_action',
            },
        ),
        migrations.CreateModel(
            name='AwardsRecognition',
            fields=[
                ('award_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='directory.member')),
            ],
            options={
                'verbose_name': 'Award/Recognition',
                'verbose_name_plural': 'Awards & Recognitions',
                'db_table': 'awards_recognition',
            },
        ),
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('academic_record_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('graduation', models.CharField(max_length=50)),
                ('member_id1', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='directory.member')),
            ],
            options={
                'verbose_name': 'Academic Background',
                'verbose_name_plural': 'Academic Backgrounds',
                'db_table': 'academic_background',
            },
        ),
        migrations.CreateModel(
            name='PublicMissionPost',
            fields=[
                ('mission_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('final_position', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='directory.member')),
            ],
            options={
                'verbose_name': 'Public Mission Post',
                'verbose_name_plural': 'Public Mission Posts',
                'db_table': 'public_mission_post',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualification_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('name_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='directory.member')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'db_table': 'qualification',
            },
        ),
        migrations.CreateModel(
            name='SpecialNote',
            fields=[
                ('note_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_written', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='directory.member')),
            ],
            options={
                'verbose_name': 'Special Note',
                'verbose_name_plural': 'Special Notes',
                'db_table': 'special_note',
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('training_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_course', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='directory.member')),
            ],
            options={
                'verbose_name': 'Training Course',
                'verbose_name_plural': 'Training Courses',
                'db_table': 'training_course',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('experience_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('final_position', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='directory.member')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'db_table': 'work_experience',
            },
        ),
    ]
