# Generated by Django 5.2.4 on 2025-07-18 06:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_adminaccount_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_photo_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
