# Generated by Django 5.2.4 on 2025-07-24 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_member_profile_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicbackground',
            old_name='member_id1',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='familydetail',
            old_name='member_id',
            new_name='member',
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.adminaccount')),
            ],
        ),
    ]
